-- Generated by Mocodo 4.2.12

CREATE TABLE Answer_Surveys (
  PRIMARY KEY (customer_Id_1, customer_Id_2),
  customer_Id_1 VARCHAR(42) NOT NULL,
  customer_Id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE birthdate (
  PRIMARY KEY (customer_Id, row_id),
  customer_Id VARCHAR(42) NOT NULL,
  row_id      VARCHAR(42) NOT NULL
);

CREATE TABLE birthdate (
  PRIMARY KEY (row_id_1, row_id_2),
  row_id_1 VARCHAR(42) NOT NULL,
  row_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE Contains_a_list_of (
  PRIMARY KEY (row_id, track_Id),
  row_id   VARCHAR(42) NOT NULL,
  track_Id VARCHAR(42) NOT NULL
);

CREATE TABLE Contains_a_list_of (
  PRIMARY KEY (customer_Id, question_Id),
  customer_Id VARCHAR(42) NOT NULL,
  question_Id VARCHAR(42) NOT NULL
);

CREATE TABLE Dim_Country (
  PRIMARY KEY (city_Id),
  city_Id   VARCHAR(42) NOT NULL,
  city_Name VARCHAR(42),
  country   VARCHAR(42),
  continent VARCHAR(42)
);

CREATE TABLE Dim_Customer (
  PRIMARY KEY (customer_Id),
  customer_Id        VARCHAR(42) NOT NULL,
  Customer_Name      VARCHAR(42),
  customer_Gender_1  VARCHAR(42),
  customer_Gender_2  VARCHAR(42),
  customer_Birthdate VARCHAR(42)
);

CREATE TABLE Dim_Date (
  PRIMARY KEY (row_id),
  row_id VARCHAR(42) NOT NULL,
  day    VARCHAR(42),
  month  VARCHAR(42),
  year   VARCHAR(42)
);

CREATE TABLE Dim_Employee (
  PRIMARY KEY (row_id),
  row_id          VARCHAR(42) NOT NULL,
  employee_Id     VARCHAR(42),
  employee_Name   VARCHAR(42),
  title           VARCHAR(42),
  reports_To      VARCHAR(42),
  employee_Gender VARCHAR(42),
  target_Year     VARCHAR(42),
  target_Q1       VARCHAR(42),
  target_Q2       VARCHAR(42),
  target_Q3       VARCHAR(42),
  target_Q4       VARCHAR(42)
);

CREATE TABLE Dim_Question (
  PRIMARY KEY (question_Id),
  question_Id       VARCHAR(42) NOT NULL,
  question_Sentence VARCHAR(42)
);

CREATE TABLE Dim_Track (
  PRIMARY KEY (track_Id),
  track_Id     VARCHAR(42) NOT NULL,
  titre        VARCHAR(42),
  album_Name   VARCHAR(42),
  Artist_Name  VARCHAR(42),
  Genre        VARCHAR(42),
  Composer     VARCHAR(42),
  Playlist     VARCHAR(42),
  Milliseconds VARCHAR(42),
  media        VARCHAR(42),
  unit_Price   VARCHAR(42)
);

CREATE TABLE Fact_Invoice (
  PRIMARY KEY (row_id),
  row_id        VARCHAR(42) NOT NULL,
  invoice_Id    VARCHAR(42),
  customer_Id   VARCHAR(42),
  city_Id       VARCHAR(42),
  employee_Id   VARCHAR(42),
  track_Id      VARCHAR(42),
  quantity      VARCHAR(42),
  invoice_Date  VARCHAR(42),
  total_Invoice VARCHAR(42)
);

CREATE TABLE Fact_Survey (
  PRIMARY KEY (customer_Id),
  customer_Id VARCHAR(42) NOT NULL,
  question_Id VARCHAR(42),
  rate_Q1     VARCHAR(42),
  rate_Q2     VARCHAR(42),
  rate_Q3     VARCHAR(42)
);

CREATE TABLE Get_a_yearly_target (
  PRIMARY KEY (row_id_1, row_id_2),
  row_id_1 VARCHAR(42) NOT NULL,
  row_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE happend_the (
  PRIMARY KEY (row_id_1, row_id_2),
  row_id_1 VARCHAR(42) NOT NULL,
  row_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE Have_to_pay (
  PRIMARY KEY (row_id, customer_Id),
  row_id      VARCHAR(42) NOT NULL,
  customer_Id VARCHAR(42) NOT NULL
);

CREATE TABLE Make_an_invoice (
  PRIMARY KEY (row_id_1, row_id_2),
  row_id_1 VARCHAR(42) NOT NULL,
  row_id_2 VARCHAR(42) NOT NULL
);

CREATE TABLE Take_place_to (
  PRIMARY KEY (row_id, city_Id),
  row_id  VARCHAR(42) NOT NULL,
  city_Id VARCHAR(42) NOT NULL
);

ALTER TABLE Answer_Surveys ADD FOREIGN KEY (customer_Id_2) REFERENCES Dim_Customer (customer_Id);
ALTER TABLE Answer_Surveys ADD FOREIGN KEY (customer_Id_1) REFERENCES Fact_Survey (customer_Id);

ALTER TABLE birthdate ADD FOREIGN KEY (row_id) REFERENCES Dim_Date (row_id);
ALTER TABLE birthdate ADD FOREIGN KEY (customer_Id) REFERENCES Dim_Customer (customer_Id);
ALTER TABLE birthdate ADD FOREIGN KEY (row_id_2) REFERENCES Dim_Date (row_id);
ALTER TABLE birthdate ADD FOREIGN KEY (row_id_1) REFERENCES Dim_Employee (row_id);

ALTER TABLE Contains_a_list_of ADD FOREIGN KEY (track_Id) REFERENCES Dim_Track (track_Id);
ALTER TABLE Contains_a_list_of ADD FOREIGN KEY (row_id) REFERENCES Fact_Invoice (row_id);
ALTER TABLE Contains_a_list_of ADD FOREIGN KEY (question_Id) REFERENCES Dim_Question (question_Id);
ALTER TABLE Contains_a_list_of ADD FOREIGN KEY (customer_Id) REFERENCES Fact_Survey (customer_Id);

ALTER TABLE Get_a_yearly_target ADD FOREIGN KEY (row_id_2) REFERENCES Dim_Date (row_id);
ALTER TABLE Get_a_yearly_target ADD FOREIGN KEY (row_id_1) REFERENCES Dim_Employee (row_id);

ALTER TABLE happend_the ADD FOREIGN KEY (row_id_2) REFERENCES Dim_Date (row_id);
ALTER TABLE happend_the ADD FOREIGN KEY (row_id_1) REFERENCES Fact_Invoice (row_id);

ALTER TABLE Have_to_pay ADD FOREIGN KEY (customer_Id) REFERENCES Dim_Customer (customer_Id);
ALTER TABLE Have_to_pay ADD FOREIGN KEY (row_id) REFERENCES Fact_Invoice (row_id);

ALTER TABLE Make_an_invoice ADD FOREIGN KEY (row_id_2) REFERENCES Dim_Employee (row_id);
ALTER TABLE Make_an_invoice ADD FOREIGN KEY (row_id_1) REFERENCES Fact_Invoice (row_id);

ALTER TABLE Take_place_to ADD FOREIGN KEY (city_Id) REFERENCES Dim_Country (city_Id);
ALTER TABLE Take_place_to ADD FOREIGN KEY (row_id) REFERENCES Fact_Invoice (row_id);
