PAR-00001 - Date de début pour la table calendrier

#date(2018, 12, 31) meta [IsParameterQuery=true, Type="Date", IsParameterQueryRequired=true]



PAR-00002 - Date de fin pour la table calendrier

#date(2020, 1, 1) meta [IsParameterQuery=true, Type="Date", IsParameterQueryRequired=true]



REQ-00001 - Table calendrier

let
    Source = List.Dates(#"PAR-00001", Duration.Days(#"PAR-00002"-#"PAR-00001")+1, #duration(1, 0, 0, 0)),
    #"00001" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"00002" = Table.RenameColumns(#"00001",{{"Column1", "Date"}}),
    #"00003" = Table.TransformColumnTypes(#"00002",{{"Date", type date}}),
    #"00004" = Table.AddColumn(#"00003", "Numéro semaine", each Date.DayOfWeek([Date], Day.Monday)+1),
    #"00005" = Table.AddColumn(#"00004", "Nom jour", each Date.DayOfWeekName([Date], "fr-FR")),
    #"00006" = Table.AddColumn(#"00005", "Numéro mois", each Date.Month([Date])),
    #"00007" = Table.AddColumn(#"00006", "Nom mois", each Date.MonthName([Date], "fr-FR")),
    #"00008" = Table.AddColumn(#"00007", "Numéro trimestre", each Date.QuarterOfYear([Date])),
    #"00009" = Table.AddColumn(#"00008", "Nom trimestre", each "T " & Number.ToText([Numéro trimestre])),
    #"00010" = Table.AddColumn(#"00009", "Année", each Date.Year([Date])),
    #"00011" = Table.AddColumn(#"00010", "Année et mois", each Date.Year([Date])*100+Date.Month([Date]))
in
    #"00011"



